### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by mike213** [helloShen/leetcode-helper#3]
I don't know why, but it generates the null pointer exception and therefore it cannot generate any files

PS D:\programming\twoSum> tree /f
D:.
│  build.xml
│  problem.properties
│  README.md
│
└─lib
        leetcode-helper.jar

PS D:\programming\twoSum> ant -version
Apache Ant(TM) version 1.10.5 compiled on July 10 2018
PS D:\programming\twoSum> ant generate
Buildfile: D:\programming\twoSum\build.xml

generate:
     [echo] problem.name = two_sum
     [java] java.lang.NullPointerException
     [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:194)
     [java]     at org.apache.tools.ant.taskdefs.Java.run(Java.java:861)
     [java]     at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
     [java]     at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
     [java]     at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
     [java]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:498)
     [java]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
     [java]     at org.apache.tools.ant.Task.perform(Task.java:350)
     [java]     at org.apache.tools.ant.Target.execute(Target.java:449)
     [java]     at org.apache.tools.ant.Target.performTasks(Target.java:470)
     [java]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
     [java]     at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
     [java]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java]     at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
     [java]     at org.apache.tools.ant.Main.runBuild(Main.java:834)
     [java]     at org.apache.tools.ant.Main.startAnt(Main.java:223)
     [java]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
     [java]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
     [java] Caused by: java.lang.NullPointerException
     [java]     at java.util.Properties$LineReader.readLine(Properties.java:434)
     [java]     at java.util.Properties.load0(Properties.java:353)
     [java]     at java.util.Properties.load(Properties.java:341)
     [java]     at com.ciaoshen.leetcode.helper.PropertyScanner.load(PropertyScanner.java:51)
     [java]     at com.ciaoshen.leetcode.helper.ProblemBuilder.main(ProblemBuilder.java:210)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:498)
     [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:218)
     [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
     [java]     ... 21 more
     [java] Java Result: -1
     [echo] Problem two_sum generated!

BUILD SUCCESSFUL
Total time: 0 seconds

Thank you

**Comment by mike213** [comment]
thanks, solved
